name: deploy
on:
  push:
    tags:
      - '*'

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 8.0.x
      - name: Submodules
        run: git submodule update --init --recursive PMDC/
      - name: Restore
        run: dotnet restore
      - name: Build Windows PMDOSetup x86
        run: dotnet publish -c Release -r win-x86 PMDOSetup/PMDOSetup.csproj
      - name: Build Windows PMDOSetup
        run: dotnet publish -c Release -r win-x64 PMDOSetup/PMDOSetup.csproj
      - name: Build Linux PMDOSetup
        run: dotnet publish -c Release -r linux-x64 PMDOSetup/PMDOSetup.csproj
      - name: Build Mac PMDOSetup
        run: dotnet publish -c Release -r osx-x64 PMDOSetup/PMDOSetup.csproj
      - name: Zip Windows PMDOSetup x86
        run: cd publish/win-x86/;zip -r setup-windows-x86.zip PMDOSetup/
      - name: Zip Windows PMDOSetup
        run: cd publish/win-x64/;zip -r setup-windows-x64.zip PMDOSetup/
      - name: Zip Linux PMDOSetup
        run: cd publish/linux-x64/;zip -r setup-linux-x64.zip PMDOSetup/
      - name: Zip Mac PMDOSetup
        run: cd publish/osx-x64/;zip -r setup-osx-x64.zip PMDOSetup/
      - name: Set Version
        run: echo "version=$(sed -En 's,<\AssemblyVersion>(.+)</AssemblyVersion>,\1,p' DataGenerator/DataGenerator.csproj)" >> $GITHUB_OUTPUT
        id: version
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Windows x86 PMDOSetup
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/win-x86/setup-windows-x86.zip
          asset_name: setup-windows-x86.zip
          asset_content_type: application/zip
      - name: Upload Windows PMDOSetup
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/win-x64/setup-windows-x64.zip
          asset_name: setup-windows-x64.zip
          asset_content_type: application/zip
      - name: Upload Linux PMDOSetup
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/linux-x64/setup-linux-x64.zip
          asset_name: setup-linux-x64.zip
          asset_content_type: application/zip
      - name: Upload Mac PMDOSetup
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/osx-x64/setup-osx-x64.zip
          asset_name: setup-osx-x64.zip
          asset_content_type: application/zip